export default {
	// Common action types

	SET_RECEIVED_USERS: "SET_RECEIVED_USERS",
	SET_CURRENT_USER: "SET_CURRENT_USER",
	SET_IS_LOADING: "SET_IS_LOADING",
	REMOVE_IS_LOADING: "REMOVE_IS_LOADING",

	// Budget action types

	GET_EXPENSE_CATEGORIES: "GET_EXPENSE_CATEGORIES",
	GET_EXPENSE_COMMENTS: "GET_EXPENSE_COMMENTS",
	SET_RECEIVED_EXPENSES: "SET_RECEIVED_EXPENSES",
	SET_RECEIVED_CURRENT_MONTH_GENERAL_INFO: "SET_RECEIVED_CURRENT_MONTH_GENERAL_INFO",
	SET_GENERAL_INFO_GROUP_COLLAPSED: "SET_GENERAL_INFO_GROUP_COLLAPSED",
	GET_MONTH_EXPENSE_LIMITS: "GET_MONTH_EXPENSE_LIMITS",
	SET_RECEIVED_MONTH_EXPENSE_LIMITS: "SET_RECEIVED_MONTH_EXPENSE_LIMITS",
	ADD_NEW_EXPENSE: "ADD_NEW_EXPENSE",
	NEW_EXPENSE_CHANGE: "NEW_EXPENSE_CHANGE",
	CLEAR_NEW_EXPENSE: "CLEAR_NEW_EXPENSE",
	TOGGLE_NEW_EXPENSE_VISIBLE: "TOGGLE_NEW_EXPENSE_VISIBLE"
};
