export default {
	// Common action types

	SET_RECEIVED_USERS: "SET_RECEIVED_USERS",
	SET_CURRENT_USER: "SET_CURRENT_USER",

	// Budget action types

	GET_EXPENSE_CATEGORIES: "GET_EXPENSE_CATEGORIES",
	GET_MONTH_EXPENSE_LIMITS: "GET_MONTH_EXPENSE_LIMITS",
	GET_EXPENSE_COMMENTS: "GET_EXPENSE_COMMENTS",
	GET_EXPENSES: "GET_EXPENSES"
};
